
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "0.3.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-test"
  version = "0.3.0-4"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "storage-volume-testsuites-avoid-tests"
  source = "github.com/pohly/kubernetes"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "master"
[[override]]
  name = "k8s.io/api"
  branch = "master"
[[override]]
  name = "k8s.io/apiserver"
  branch = "master"
[[override]]
  name = "k8s.io/kube-aggregator"
  branch = "master"
[[override]]
  name = "k8s.io/client-go"
  branch = "master"

[[override]]
  # kubernetes/pkg/util/parsers/parsers.go needs the new reference.ParseNormalizedNamed
  # API call, which isn't yet in any stable release.
  name = "github.com/docker/distribution"
  branch = "master"

# This prevents dep from pulling an empty repo for gopkg.in/fsnotify.v1,
# something that it does not recover from.
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"
