apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pmem-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-pmem-sc # defined in pmem-csi.yaml
